blog/urls.py
from django.urls import path
from .views import render_post, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_post, name="posts"),#este es el path origen de urls.py dentro de la app "post", esta url viene redirigida desde la url del proyecto "django_portfolio". Nota: debe importar la vista desde .views y path desde django.urls    
    path('<int:post_id>', post_detail, name='post_detail'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))#se usa include para que redireccione de la url del proyecto "django_portfolio" a la url de la app "blog", nota: hay que importar include desde django.urls
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from django.db.models.fields import URLField

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)
    url = URLField(blank=True)
    pdf_1 = models.FileField(upload_to='pdfs/', null=True, blank=True)
    pdf_2 = models.FileField(upload_to='pdfs/', null=True, blank=True)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)
    
    def __str__(self):#muestra la impresion en el panel de administrador
        return self.title + ' - by ' + self.url

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_post(request):
    posts = Post.objects.all()
    #posts = get_object_or_404(Post)
    return render(request, 'posts.html', {
        'posts': posts
    })

def post_detail(request, post_id):
    #post = Post.objects.filter(id=post_id)
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {
        'post': post,
    })

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {
        'projects': projects
    })

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

<div class="text-center">
    <h1>{{post.title}}</h1>
    <h3 class="my-2 h5 text-light">{{post.date|date:'F jS Y'}}</h3>
    
    <div class="row justify-content-center">

        <div class="card col-4 bg-black">
            <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
        </div>
    
        <div class="my-4">
            <p class="text-justify">{{post.description|safe}}</p>
        </div>
        
        <a href="{{post.pdf_1.url}}" class="btn btn-primary my-3 rounded-0 btn-sm text-light" target="_blank">{{post.pdf_1}}</a>  
    
        <a href="{{post.pdf_2.url}}" class="btn btn-primary my-3 rounded-0 btn-sm text-light" target="_blank">{{post.pdf_2}}</a>  
       
    </div>
</div>


{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

<h1>Post</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
    
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
        
        
            <div class="col-9">
                <h1>{{post.title}}</h1>
                <p>{{post.description|striptags|truncatechars:100}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary" target="_blank">{{post.title}}</a>    
                <p>{{post.date|date:'M d Y'|upper}}</p>
            </div>

        </div>  
        
    
    
    </div>    
</div>

{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<div class="container text-justify bg-black">
    <div class="row justify-content-start">
        <div class="card col-4 bg-black">
            <img src="{% static 'portfolio/EJ_coder_2.png' %}" alt=""/>
        </div>
    
    
        <div class="col-8">
            <h1>I'm <strong>Edwuard Jorge</strong></h1>
            <h3>Python FullStack Developer - Django | React | JS | Oracle Forms and Reports | C | Database: Oracle DB, PostgreSql, PL-SQL</h3>
            <p>I am a senior specialist in systems development with more than 18 years of experience between languages: Python, Django, React, JavaScript, Oracle Forms and Reports, C, React. I am characterized by the curiosity to learn new technologies and obtain new opportunities to grow professionally and personally, always focused on giving the best of myself.</p>
            <a href="{% static 'portfolio/Resume Python Developer.pdf' %}" class="btn btn-primary   my-3"
                target="_blank" >Download Resume</a>
        </div>
    </div>
</div>


<div class="row my-4 text-center">
    <h3>My Project</h3>
    <p>Check out part of my work bellow</p>

    {% for project in projects %}

    <div class="card bg-black col-md-4 p-4 mx-auto" style="width: 18rem;">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top bg-black"/>
        
        <div class="card-text text-light">
            <h2>{{project.title}}</h2>
            <p>{{project.description}}</p>

            {% if project.url %}
                <a href="{{project.url}}" class="btn bg-black rounded-0 btn-sm text-light" target="_blank">{{project.url}}</a>
            {% endif %}

        </div>
      </div>



    {% endfor %}

</div>
{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Portfolio</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">

</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}        
    </div>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Edwuard Jorge</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>{#blog:posts accede a la ventana posts a traves de la variable app_name y con el comendo : #}
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Resume Python Developer.pdf' %}" target="_blank">Download Resume</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>